const FOOD_DATA = {
    red: [
        { id: 'redbean', zh: '紅豆', ja: '小豆', category: 'red', img: 'images/foods/redbean.png' },
        { id: 'dragonfruit', zh: '紅龍果', ja: 'ドラゴンフルーツ', category: 'red', img: 'images/foods/dragonfruit.png' },
        { id: 'tomato', zh: '番茄', ja: 'トマト', category: 'red', img: 'images/foods/tomato.png' },
        { id: 'watermelon', zh: '西瓜', ja: 'スイカ', category: 'red', img: 'images/foods/watermelon.png' },
        { id: 'strawberry', zh: '草莓', ja: 'いちご', category: 'red', img: 'images/foods/strawberry.png' },
        { id: 'cherry', zh: '櫻桃', ja: 'さくらんぼ', category: 'red', img: 'images/foods/cherry.png' },
        { id: 'apple', zh: '蘋果', ja: 'りんご', category: 'red', img: 'images/foods/apple.png' },
        { id: 'jujube', zh: '紅棗', ja: 'ナツメ', category: 'red', img: 'images/foods/jujube.png' },
        { id: 'goji', zh: '枸杞', ja: 'クコの実', category: 'red', img: 'images/foods/goji.png' },
        { id: 'beetroot', zh: '甜菜根', ja: 'ビートルート', category: 'red', img: 'images/foods/beetroot.png' },
        { id: 'beef', zh: '牛肉', ja: '牛肉', category: 'red', img: 'images/foods/beef.png' },
        { id: 'pork', zh: '豬肉', ja: '豚肉', category: 'red', img: 'images/foods/pork.png' },
        { id: 'mutton', zh: '羊肉', ja: 'マトン', category: 'red', img: 'images/foods/mutton.png' },
        { id: 'waxapple', zh: '蓮霧', ja: 'レンブ', category: 'red', img: 'images/foods/waxapple.png' },
        { id: 'cranberry', zh: '蔓越莓', ja: 'ク蘭ベリー', category: 'red', img: 'images/foods/cranberry.png' },
        { id: 'hibiscus', zh: '洛神花', ja: 'ハイビスカス', category: 'red', img: 'images/foods/hibiscus.png' },
        { id: 'bellpepper', zh: '甜椒', ja: '赤ピーマン', category: 'red', img: 'images/foods/bellpepper.png' },
        { id: 'chili', zh: '辣椒', ja: '唐辛子', category: 'red', img: 'images/foods/chili.png' },
        { id: 'pomegranate', zh: '石榴', ja: 'ザクロ', category: 'red', img: 'images/foods/pomegranate.png' },
        { id: 'shrimp', zh: '蝦子', ja: 'エビ', category: 'red', img: 'images/foods/shrimp.png' }
    ],
    orange: [
        { id: 'carrot', zh: '胡蘿蔔', ja: '人参', category: 'orange', img: 'images/foods/carrot.png' },
        { id: 'persimmon', zh: '柿子', ja: '柿', category: 'orange', img: 'images/foods/persimmon.png' },
        { id: 'papaya', zh: '木瓜', ja: 'パパイヤ', category: 'orange', img: 'images/foods/papaya.png' },
        { id: 'orange', zh: '柳丁', ja: 'オレンジ', category: 'orange', img: 'images/foods/orange.png' },
        { id: 'mandarin', zh: '橘子', ja: 'みかん', category: 'orange', img: 'images/foods/mandarin.png' },
        { id: 'loquat', zh: '枇杷', ja: 'びわ', category: 'orange', img: 'images/foods/loquat.png' },
        { id: 'salmon', zh: '鮭魚', ja: '鮭', category: 'orange', img: 'images/foods/salmon.png' },
        { id: 'cantaloupe', zh: '哈密瓜', ja: 'メロン', category: 'orange', img: 'images/foods/cantaloupe.png' },
        { id: 'peach', zh: '水蜜桃', ja: '桃', category: 'orange', img: 'images/foods/peach.png' },
        { id: 'pineapple', zh: '鳳梨', ja: 'パイナップル', category: 'orange', img: 'images/foods/pineapple.png' },
        { id: 'physalis', zh: '燈籠果', ja: 'ほおずき', category: 'orange', img: 'images/foods/physalis.png' },
        { id: 'salmonroe', zh: '鮭魚卵', ja: 'いくら', category: 'orange', img: 'images/foods/salmonroe.png' },
        { id: 'seaurchin', zh: '海膽', ja: 'ウニ', category: 'orange', img: 'images/foods/seaurchin.png' },
        { id: 'mango', zh: '芒果', ja: 'マンゴー', category: 'orange', img: 'images/foods/mango.png' },
        { id: 'pumpkin', zh: '南瓜', ja: 'かぼちゃ', category: 'orange', img: 'images/foods/pumpkin.png' },
        { id: 'honey', zh: '蜂蜜', ja: '蜂蜜', category: 'orange', img: 'images/foods/honey.png' },
        { id: 'turmeric', zh: '薑黃', ja: 'ターメリック', category: 'orange', img: 'images/foods/turmeric.png' },
        { id: 'wheat', zh: '小麥', ja: '小麦', category: 'orange', img: 'images/foods/wheat.png' },
        { id: 'cheese', zh: '起司', ja: 'チーズ', category: 'orange', img: 'images/foods/cheese.png' },
        { id: 'flowercrab', zh: '花蟹', ja: '渡り蟹', category: 'orange', img: 'images/foods/flowercrab.png' }
    ],
    light: [
        { id: 'rice', zh: '稻米', ja: '米', category: 'light', img: 'images/foods/rice.png' },
        { id: 'tofu', zh: '豆腐', ja: '豆腐', category: 'light', img: 'images/foods/tofu.png' },
        { id: 'radish', zh: '白蘿蔔', ja: '大根', category: 'light', img: 'images/foods/radish.png' },
        { id: 'beansprouts', zh: '豆芽菜', ja: 'もやし', category: 'light', img: 'images/foods/beansprouts.png' },
        { id: 'banana', zh: '香蕉', ja: 'バナナ', category: 'light', img: 'images/foods/banana.png' },
        { id: 'brownrice', zh: '糙米', ja: '玄米', category: 'light', img: 'images/foods/brownrice.png' },
        { id: 'onion', zh: '洋蔥', ja: '玉ねぎ', category: 'light', img: 'images/foods/onion.png' },
        { id: 'garlic', zh: '大蒜', ja: 'にんにく', category: 'light', img: 'images/foods/garlic.png' },
        { id: 'waterbamboo', zh: '茭白筍', ja: 'マコモダケ', category: 'light', img: 'images/foods/waterbamboo.png' },
        { id: 'yam', zh: '山藥', ja: '山芋', category: 'light', img: 'images/foods/yam.png' },
        { id: 'cabbage', zh: '高麗菜', ja: 'キャベツ', category: 'light', img: 'images/foods/cabbage.png' },
        { id: 'cauliflower', zh: '花椰菜', ja: 'カリフラワー', category: 'light', img: 'images/foods/cauliflower.png' },
        { id: 'corn', zh: '玉米', ja: 'トウモロコシ', category: 'light', img: 'images/foods/corn.png' },
        { id: 'pear', zh: '水梨', ja: '梨', category: 'light', img: 'images/foods/pear.png' },
        { id: 'sweetpotato', zh: '地瓜', ja: 'さつまいも', category: 'light', img: 'images/foods/sweetpotato.png' },
        { id: 'egg', zh: '雞蛋', ja: '卵', category: 'light', img: 'images/foods/egg.png' },
        { id: 'kingoyster', zh: '杏鮑菇', ja: 'エリンギ', category: 'light', img: 'images/foods/kingoyster.png' },
        { id: 'lemon', zh: '檸檬', ja: 'レモン', category: 'light', img: 'images/foods/lemon.png' },
        { id: 'threadfin', zh: '午仔魚', ja: 'ツバメコノシロ', category: 'light', img: 'images/foods/threadfin.png' },
        { id: 'bittermelon', zh: '苦瓜', ja: 'ゴーヤ', category: 'light', img: 'images/foods/bittermelon.png' }
    ],
    dark: [
        { id: 'blackbean', zh: '黑豆', ja: '黒豆', category: 'dark', img: 'images/foods/blackbean.png' },
        { id: 'blacksesame', zh: '黑芝麻', ja: '黒ごま', category: 'dark', img: 'images/foods/blacksesame.png' },
        { id: 'woodear', zh: '黑木耳', ja: '木耳', category: 'dark', img: 'images/foods/woodear.png' },
        { id: 'purplerice', zh: '紫米', ja: '黒米', category: 'dark', img: 'images/foods/purplerice.png' },
        { id: 'eggplant', zh: '茄子', ja: '茄子', category: 'dark', img: 'images/foods/eggplant.png' },
        { id: 'blueberry', zh: '藍莓', ja: 'ブルーベリー', category: 'dark', img: 'images/foods/blueberry.png' },
        { id: 'mulberry', zh: '桑葚', ja: '桑の実', category: 'dark', img: 'images/foods/mulberry.png' },
        { id: 'grape', zh: '葡萄', ja: 'ぶどう', category: 'dark', img: 'images/foods/grape.png' },
        { id: 'grassjelly', zh: '仙草', ja: '仙草ゼリー', category: 'dark', img: 'images/foods/grassjelly.png' },
        { id: 'shiitake', zh: '香菇', ja: '椎茸', category: 'dark', img: 'images/foods/shiitake.png' },
        { id: 'kelp', zh: '海帶', ja: '昆布', category: 'dark', img: 'images/foods/kelp.png' },
        { id: 'seaweed', zh: '紫菜', ja: '海苔', category: 'dark', img: 'images/foods/seaweed.png' },
        { id: 'pepper', zh: '胡椒', ja: '胡椒', category: 'dark', img: 'images/foods/pepper.png' },
        { id: 'centuryegg', zh: '皮蛋', ja: 'ピータン', category: 'dark', img: 'images/foods/centuryegg.png' },
        { id: 'blackdate', zh: '黑棗', ja: '黒なつめ', category: 'dark', img: 'images/foods/blackdate.png' },
        { id: 'silkie', zh: '烏骨雞', ja: '烏骨鶏', category: 'dark', img: 'images/foods/silkie.png' },
        { id: 'plum', zh: '李子', ja: 'スモモ', category: 'dark', img: 'images/foods/plum.png' },
        { id: 'perilla', zh: '紫蘇', ja: '大葉', category: 'dark', img: 'images/foods/perilla.png' },
        { id: 'fig', zh: '無花果', ja: '無花果', category: 'dark', img: 'images/foods/fig.png' },
        { id: 'cocoa', zh: '可可豆', ja: 'カカオ豆', category: 'dark', img: 'images/foods/cocoa.png' }
    ],
    green: [
        { id: 'bokchoy', zh: '青江菜', ja: 'チンゲン菜', category: 'green', img: 'images/foods/bokchoy.png' },
        { id: 'spinach', zh: '菠菜', ja: 'ほうれん草', category: 'green', img: 'images/foods/spinach.png' },
        { id: 'waterspinach', zh: '空心菜', ja: '空芯菜', category: 'green', img: 'images/foods/waterspinach.png' },
        { id: 'sweetpotatoleaf', zh: '地瓜葉', ja: 'サツマイモの葉', category: 'green', img: 'images/foods/sweetpotatoleaf.png' },
        { id: 'broccoli', zh: '青花菜', ja: 'ブロッコリー', category: 'green', img: 'images/foods/broccoli.png' },
        { id: 'luffa', zh: '絲瓜', ja: 'ヘチマ', category: 'green', img: 'images/foods/luffa.png' },
        { id: 'asparagus', zh: '蘆筍', ja: 'アスパラガス', category: 'green', img: 'images/foods/asparagus.png' },
        { id: 'cucumber', zh: '小黃瓜', ja: 'きゅうり', category: 'green', img: 'images/foods/cucumber.png' },
        { id: 'greenpepper', zh: '青椒', ja: 'ピーマン', category: 'green', img: 'images/foods/greenpepper.png' },
        { id: 'okra', zh: '秋葵', ja: 'オクラ', category: 'green', img: 'images/foods/okra.png' },
        { id: 'chives', zh: '韭菜', ja: 'ニラ', category: 'green', img: 'images/foods/chives.png' },
        { id: 'kiwi', zh: '奇異果', ja: 'キウイ', category: 'green', img: 'images/foods/kiwi.png' },
        { id: 'guava', zh: '芭樂', ja: 'グアバ', category: 'green', img: 'images/foods/guava.png' },
        { id: 'avocado', zh: '酪梨', ja: 'アボカド', category: 'green', img: 'images/foods/avocado.png' },
        { id: 'cilantro', zh: '香菜', ja: 'パクチー', category: 'green', img: 'images/foods/cilantro.png' },
        { id: 'edamame', zh: '毛豆', ja: '枝豆', category: 'green', img: 'images/foods/edamame.png' },
        { id: 'mungbean', zh: '綠豆', ja: '緑豆', category: 'green', img: 'images/foods/mungbean.png' },
        { id: 'matcha', zh: '抹茶', ja: '抹茶', category: 'green', img: 'images/foods/matcha.png' },
        { id: 'celery', zh: '芹菜', ja: 'セロリ', category: 'green', img: 'images/foods/celery.png' },
        { id: 'dragonmustache', zh: '龍鬚菜', ja: '龍鬚菜', category: 'green', img: 'images/foods/dragonmustache.png' }
    ]
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = FOOD_DATA;
}
