const LANGUAGES = {
    'zh-TW': {
        // UI Text
        ui_egg_name: '🥚 蛋',
        ui_egg: '蛋',
        ui_hunger: '🍎 飽食度',
        ui_happy: '😊 快樂度',
        ui_combat_start: '戰鬥開始！',
        ui_opponent: '對手',
        ui_player: '玩家',
        ui_rps_title: '✌️ 猜拳遊戲 ✌️',
        ui_rps_desc: '輸入: <strong>scissors</strong>, <strong>rock</strong>, 或 <strong>paper</strong>',
        ui_scissors: '剪刀',
        ui_rock: '石頭',
        ui_paper: '布',
        ui_feed_title: '🍎 餵食寵物 🍎',
        ui_feed_desc: '選擇要餵食的水果：',
        ui_back: '返回',
        ui_close: '✕ 關閉',
        ui_dex_title: '📖 圖鑑',
        ui_dex_progress: '收集進度：',
        ui_hof_title: '🏆 英雄榜',
        ui_clean_title: '🚿 環境清理 🚿',
        ui_clean_hint: '輸入蟲蟲的英文名稱來清除牠！',
        ui_hof_desc: '記念那些曾經陪伴我們的夥伴',
        ui_off: '關閉',
        ui_on: '開啟',
        ui_hit: '中了',
        ui_miss: '沒中',
        ui_blocked: '格擋成功',
        ui_dmg_taken: '格擋失敗, HP -{0}',
        ui_unknown: '未知',
        ui_unknown_pet: '未知寵物',
        ui_trait: '特性：',
        ui_stage_baby: '▸ 初始型態',
        ui_stage_1: '▸ 一階進化',
        ui_stage_2: '▸ 二階進化',
        ui_lang_title: '🌐 語言設定 / Language 🌐',
        ui_lang_desc: '選擇遊戲語言 / Select Game Language:',
        ui_lang_tooltip: '輸入指令 lang 以開啟語言選單',
        ui_cmd_prompt: '輸入指令 (英文)...',
        ui_feed_placeholder: '輸入水果名或 back 返回...',
        ui_clean_placeholder: '輸入蟲蟲的英文名稱...',
        ui_lang_placeholder: 'english / chinese / japanese / back',
        ui_hof_placeholder: '輸入 back 返回...',
        ui_rps_placeholder: '輸入 scissors, rock, 或 paper...',
        ui_knock_desc: '敲敲這顆蛋，看看會發生什麼',
        ui_clean_desc: '幫寵物洗澡，清理環境',
        ui_play_desc: '跟寵物玩猜拳遊戲',
        ui_battle_desc: '挑戰野外戰鬥 (飽食度需 >= 2)',
        ui_rename_desc: '幫你的夥伴換個新名字',
        ui_dex_desc: '查看已收集的小寵物圖鑑',
        ui_save_desc: '下載存檔檔案以便下次遊玩',
        ui_load_desc: '上傳並載入之前的遊戲進度',
        ui_evo1_timer: '一階進化',
        ui_evo2_timer: '二階進化',
        ui_death_timer: '安然離世',
        ui_evo_ready: '{0}：隨時可能發生',
        ui_evo_time_d: '{0}：剩餘 {1}天 {2}時 {3}分',
        ui_evo_time: '{0}：剩餘 {1}時 {2}分',
        
        // Fruit Names
        fruit_apple: '蘋果',
        fruit_orange: '橘子',
        fruit_lemon: '檸檬',
        fruit_grape: '葡萄',
        fruit_guava: '芭樂',

        // System messages
        msg_feed_prompt: '🍎 請輸入顯示的水果英文名來餵食，或輸入 back 返回',
        msg_feed_cant_battle: '⚔️ 戰鬥中無法餵食！',
        msg_feed_full: '🍎 飽食度已滿，不需要餵食！',
        msg_dex_new: '📖 圖鑑新增：',
        msg_save_invalid: '❌ 無效的存檔檔案！',
        msg_save_corrupt: '❌ 讀取存檔失敗：檔案格式錯誤',
        msg_save_loaded: '📂 存檔載入成功！',
        msg_save_downloaded: '💾 存檔已下載: ',
        msg_time_passed_hm: '⏰ 距離上次存檔已過 {0} 小時 {1} 分',
        msg_time_passed_m: '⏰ 距離上次存檔已過 {0} 分鐘',
        msg_come_back: ' 回來了！',
        msg_evolve: '✨ {0} 進化為 {1}！',
        msg_evolve_stage1: '📊 成長階段已達成一階進化！',
        msg_hof_empty: '目前尚無英雄紀錄',
        msg_hof_stats: '⚔️ 戰績: {0}勝 / {1}戰 (勝率: {2}%)',
        msg_rps_draw: '🤝 平手！雙方都出 {0}',
        msg_rps_win: '✌️ 你贏了！{0} 看起來有點失落...',
        msg_rps_lose: '🎉 {0} 贏了！現在感覺{1}',
        msg_status_feed: '📊 餵食統計 — {0}',
        msg_status_overall: '🏨 狀態總結 — 🍔 飽食: {0}  😊 快樂: {1}  🚿 環境: {2}',
        msg_status_battle: '⚔️ 戰績統計 — 勝場: {0} / 總對戰: {1} (勝率: {2}%)',
        msg_status_evo1: '🔮 依目前狀態，一階進化預測: {0}（{1}）',
        msg_status_evo2: '🔮 依目前狀態，二階進化預測: {0}（{1}）',
        msg_status_evo_max: '⏳ 寵物已達到最終階段，壽命剩餘: 5天',
        msg_welcome_back: '歡迎回來！你的 {0} 正等著你！',
        msg_rps_start: '✌️ 猜拳遊戲開始！請輸入你的選擇...',
        msg_rps_invalid: '❌ 請輸入: scissors, rock, 或 paper',
        msg_feed_invalid: '❌ 請輸入水果名: {0}',
        msg_feed_success: '{0} 用{1}餵食 {2}！現在感覺{3}',
        msg_save_downloaded: '💾 存檔已下載: {0}',
        msg_save_loaded: '📂 存檔載入成功！{0} 回來了！',
        msg_save_invalid: '❌ 無效的存檔檔案！',
        msg_time_passed: '⏰ 距離上次存檔已過 {0}',
        msg_rename_prompt: '✏️ 請輸入 {0} 的新名字:',
        msg_rename_empty: '❌ 名字不能為空！',
        msg_rename_long: '❌ 名字最多10個字！',
        msg_rename_success: '✏️ {0} 改名為 {1}！',
        msg_clean_cant_battle: '⚔️ 戰鬥中無法清潔！',
        msg_clean_start: '🧹 發現蟲蟲！請輸入牠的英文名稱。環境髒亂會影響寵物成長喔。',
        msg_clean_wrong: '❌ 名稱錯誤！仔細觀察蟲蟲並再試一次。',
        msg_clean_unnecessary: '🚿 環境很乾淨，不需要清潔！',
        msg_clean_success: '🚿 清潔完成！環境變得{0}',
        msg_play_cant_battle: '⚔️ 戰鬥中無法玩猜拳！',
        msg_battle_already: '⚔️ 戰鬥已經在進行中！',
        msg_battle_egg: '🥚 蛋還太小，無法戰鬥！',
        msg_battle_tired: '💤 寵物太累了 (飽食度 < 2)，請餵食！',
        msg_battle_no_opponent: '❌ 找不到對手，請稍後再試。',
        msg_battle_win: '🎉 戰鬥勝利！{0} 感到非常驕傲，心情變好了！',
        msg_battle_lose: '💔 戰鬥落敗... {0} 夾著尾巴逃跑了。',
        msg_battle_export_success: '💾 戰鬥詳細紀錄已儲存為 battle_log.txt',
        msg_battle_export_download: '💾 戰鬥詳細紀錄已下載 (單機模式)',
        msg_egg_intro: '✨ 你獲得了一顆新蛋！輸入 knock 來敲敲看吧！',
        msg_egg_knock: '🥚 蛋動了一下，輸入 knock 來敲敲看吧！',
        msg_cmd_unknown_egg: '❌ 未知指令。可用: knock, dex, save, load',
        msg_cmd_unknown: '❌ 未知指令。請輸入有效指令。',
        msg_lang_set: '🌐 語言已設定為 {0}。',
        msg_lang_invalid: '❌ 無效的語言選擇。請輸入: english, chinese, 或 japanese',
        msg_battle_log_toggle: '⚔️ 詳細戰鬥訊息已{0}',
        msg_knock: '✊ 咚咚！',
        msg_egg_hatch: '✨ 孵化了！{0}誕生了！',
        msg_time_passed_hm: '⏰ 距離上次存檔已過 {0} 小時 {1} 分',
        msg_time_passed_m: '⏰ 距離上次存檔已過 {0} 分',
        msg_save_failed: '❌ 讀取存檔失敗：檔案格式錯誤',
        msg_dex_evolve: '✨ {0} 進化為 {1}！',
        msg_dex_new: '📖 圖鑑新增：',
        msg_hof_invalid: '❌ 無效指令。輸入 back 返回。',
        msg_dex_invalid: '❌ 無效指令。輸入 back 返回。',

        msg_debug_egg: '🥚 蛋階段無法執行此操作！',
        msg_debug_stat: '🛠️ [DEBUG] {0} 已設定為 {1}',
        msg_debug_reset: '⚠️ [DEBUG] 遊戲存檔已重設！',
        msg_debug_dex_all: '🛠️ [DEBUG] 已解鎖所有 {0} 種寵物圖鑑！',
        msg_debug_dex_clear: '⚠️ [DEBUG] 圖鑑已清空！',
        msg_debug_death_err: '❌ [DEBUG] 只有二階進化後的型態才能執行此操作！',
        msg_debug_hof_clear: '⚠️ [DEBUG] 英雄榜已清空！',
        msg_debug_egg_hatch_err: '❌ [DEBUG] 目前是蛋階段，請先使用 knock 孵化！',
        msg_debug_evo_err: '❌ [DEBUG] 寵物已達到最終階段，無法再進化！',
        msg_debug_evo1: '✨ [DEBUG] 手動觸發一階進化！',
        msg_debug_evo2: '✨ [DEBUG] 手動觸發二階進化！',
        msg_debug_feed: '🛠️ [DEBUG] {0} 增加 {1}，目前總計: {2}',
        msg_debug_feed_usage: '❌ [DEBUG] 用法: debugfeed [水果名] [數量]',
        msg_debug_setpet: '🛠️ [DEBUG] 寵物型態已強制設定為 {0} {1}！',
        msg_debug_setpet_usage: '❌ [DEBUG] 用法: debugsetpet [型態ID]',

        pet_baby: '小白點',
        pet_desc_baby: '小型白色生命體，有眼睛，會輕微跳動',
        pet_baby_black: '小黑點',
        pet_desc_baby_black: '深邃的小黑點，散發著微弱的幽暗氣息',
        pet_mud_pig: '泥皮豬',
        pet_desc_mud_pig: '全身沾滿泥巴的小豬，喜歡髒亂的環境',
        pet_rainbow_dove: '虹羽鴿',
        pet_desc_rainbow_dove: '羽毛閃耀著五彩光芒的鴿子，象徵著均衡',
        pet_fire_rat: '炎尾鼠',
        pet_desc_fire_rat: '尾巴燃燒著火焰的小鼠，個性十分火爆',
        pet_sprout_deer: '芽角鹿',
        pet_desc_sprout_deer: '頭上長著嫩芽的小鹿，熱愛大自然',
        pet_spark_cat: '閃毛貓',
        pet_desc_spark_cat: '皮毛帶有靜電的小貓，動作非常敏捷',
        pet_shadow_fox: '影球狐',
        pet_desc_shadow_fox: '能操縱影子球的狐狸，散發著神祕感',
        pet_fist_lion: '拳尾獅',
        pet_desc_fist_lion: '尾巴像拳頭一樣強壯的獅子，力量驚人',
        pet_shadow_spider: '影刺蛛',
        pet_desc_shadow_spider: '潛伏在陰影中的蜘蛛，帶有危險的尖刺',
        pet_shadow_turtle: '冥甲龜',
        pet_desc_shadow_turtle: '背負著沉重冥界鎧甲的烏龜，防禦力極高',
        pet_toxic_boar: '毒沼牙豬',
        pet_desc_toxic_boar: '生活在毒液沼澤中的巨豬，尖牙帶有劇毒',
        pet_junk_boar: '重甲廢豬',
        pet_desc_junk_boar: '身上堆滿雜物並以此為護甲的野豬',
        pet_ghost_boar: '怨泥影豬',
        pet_desc_ghost_boar: '由怨念與泥土構成的幽靈豬',
        pet_aurora_eagle: '極光天鷹',
        pet_desc_aurora_eagle: '盤旋在北極上空的雄鷹，雙翼如同極光',
        pet_chaos_crow: '亂彩鴉',
        pet_desc_chaos_crow: '羽毛顏色雜亂無章的烏鴉，代表著渾沌',
        pet_flash_falcon: '炫光隼',
        pet_desc_flash_falcon: '速度極快的獵隼，身姿如同閃光',
        pet_blast_rat: '爆焰巨鼠',
        pet_desc_blast_rat: '能體現爆炸性威力的巨大老鼠',
        pet_ash_rat: '灰燼潛鼠',
        pet_desc_ash_rat: '能在灰燼中穿梭而不被發現的灰鼠',
        pet_flame_rat: '烈焰獵鼠',
        pet_desc_flame_rat: '全身纏繞火燄的獵捕專家',
        pet_tree_deer: '古樹巨鹿',
        pet_desc_tree_deer: '與古老樹木合而為一的巨大鹿',
        pet_wind_deer: '疾風草鹿',
        pet_desc_wind_deer: '奔跑速度如疾風般的草食獸',
        pet_wilt_deer: '枯葉隱鹿',
        pet_desc_wilt_deer: '善於利用枯葉色彩隱蔽自己的鹿',
        pet_static_cat: '靜電影貓',
        pet_desc_static_cat: '全身充滿高壓靜電的黑貓',
        pet_hunger_cat: '飢雷迅貓',
        pet_desc_hunger_cat: '因飢餓而變得異常兇猛的雷電貓',
        pet_thunder_cat: '雷霆戰貓',
        pet_desc_thunder_cat: '身經百戰且能操縱雷霆的戰鬥貓',
        pet_phantom_fox: '幻影舞狐',
        pet_desc_phantom_fox: '身姿如同幻影般優美的舞蹈狐狸',
        pet_creep_fox: '飢影詭狐',
        pet_desc_creep_fox: '隱藏在暗處監視一切的詭異狐狸',
        pet_abyss_fox: '深淵影狐',
        pet_desc_abyss_fox: '來自深淵，全身黑暗的影之狐',
        pet_mega_lion: '巨拳戰獅',
        pet_desc_mega_lion: '擁有毀滅性拳擊威力的格鬥獅子',
        pet_dirty_lion: '污鎧鬥獅',
        pet_desc_dirty_lion: '身披污垢與汗水之鎧的勇猛對手',
        pet_rage_lion: '憤怒狂獅',
        pet_desc_rage_lion: '陷入狂暴狀態，無人能檔的猛獅',
        pet_doom_spider: '厄命鐮蛛',
        pet_desc_doom_spider: '揮舞著死亡鐮刀腳的巨大蜘蛛',
        pet_venom_spider: '劇毒晶蛛',
        pet_desc_venom_spider: '全身佈滿劇毒結晶的恐怖蜘蛛',
        pet_void_spider: '虛空織網蛛',
        pet_desc_void_spider: '在虛空中編織銀網的神祕蜘蛛',
        pet_bone_turtle: '荒蕪骨龜',
        pet_desc_bone_turtle: '甲殼化為白骨的荒野巨龜',
        pet_hellfire_turtle: '獄火岩龜',
        pet_desc_hellfire_turtle: '背負著岩漿與地獄之火的巨龜',
        pet_mirage_turtle: '幽冥幻龜',
        pet_desc_mirage_turtle: '半透明且能產生幻象的冥界烏龜',

        msg_leave_hunger: '{0} 因為太餓了，決定離開去尋找食物...',
        msg_leave_happy: '{0} 太不開心了，悄悄地離開了...',
        msg_leave_poop: '{0} 受不了髒亂的環境，離開了...',
        msg_leave_prompt: '想要再領養一隻新的寵物蛋嗎？',
        msg_leave_cmd: '請在對話框輸入 egg 重新開始',
        msg_death: '{0} 已經安然離世了...',
        msg_death_sub: '牠的一生非常精彩，我們永遠懷念牠。',
        msg_battle_start: '遇到野生了 {0}！戰鬥開始！',
        msg_battle_ability: '[{0}] {1}',
        msg_battle_dmg: '感到體力下降了',
        msg_battle_heal: '感到體力恢復了',
        msg_battle_atk_up: '攻擊變準確',
        msg_battle_atk_down: '攻擊變難以命中',
        msg_battle_def_up: '防禦力提升了',
        msg_battle_def_down: '防禦力下降了',
        msg_battle_spd_up: '動作變敏捷了',
        msg_battle_spd_down: '身體變沉重了',
        msg_battle_dmg_up: '造成的傷害增強了',
        msg_battle_turn: '第 {0} 回合 - 速度對決！',
        msg_battle_attack: '{0} 發動攻擊！',
        msg_battle_blocked: '{0} 成功擋下了攻擊！',
        msg_battle_hit: '{0} 受到了傷害！',
        msg_battle_miss: '{0} 攻擊失誤...',
        msg_battle_debug_spd: '🎲 [BATTLE] 第 {0} 回合速度：玩家({1}) vs 對手({2})',
        msg_battle_debug_atk: '🎲 [BATTLE] {0} 攻擊擲骰: {1} (ATK:{2}) ({3})',
        msg_battle_debug_def: '🎲 [BATTLE] {0} 防禦擲骰: {1} (DEF:{2}) ({3})',

        battle_rest_name: '休息',
        battle_rest_msg: '{0} 正在休息中，無法攻擊',
        battle_crit_fail_name: '致命失敗',
        battle_crit_fail_msg: '{0} 致命失敗！攻擊太過猛烈反而傷到了自己！',
        battle_crit_fail_debug: '{0} 丟出了 20！攻擊太過猛烈反而傷到了自己！',
        battle_weak_name: '暴露弱點',
        battle_weak_msg: '{0} 暴露弱點！受到額外傷害',
        battle_weak_debug: '{0} 丟出了 20！致命弱點暴露，受到了額外傷害',
        battle_ability_dmg: '{0} 受到 {1} 影響，體力下降了',
        battle_ability_heal: '{0} 發動 {1}，恢復了體力',
        battle_ability_stat: '{0} 受 {1} 影響，{2} {3}',
        battle_ability_stat_perm: '{0} 受 {1} 影響，{2} 永久 {3}',
        battle_ability_rest: '{0} 受 {1} 影響，下回合將休息不攻擊',
        battle_ability_mode: '{0} 採取 {1} 判定',
        battle_ability_bonus: '發動 {0}，造成了額外傷害',

        // Abilities (Traits)
        ability_feather_name: '爆閃羽毛',
        ability_feather_desc: '被攻擊命中後，使對手下回合休息且攻擊變難以命中',
        ability_vweb_name: '虛空之網',
        ability_vweb_desc: '受傷且對手命中骰點數極低時，對手用力過猛，傷害無效化（並恢復體力）',
        ability_escape_name: '快速脫離',
        ability_escape_desc: '回合中當自己取得先手且命中對手時，使對手這回合攻擊變難以命中',
        ability_burnpunch_name: '灼燒之拳',
        ability_burnpunch_desc: '攻擊命中且大獲全勝時，造成的傷害增強了（每場限一次）',
        ability_fireball_name: '投擲火球',
        ability_fireball_desc: '戰鬥開始時，發動奇襲若命中則使對手感到體力下降',
        ability_nrecover_name: '自然恢復',
        ability_nrecover_desc: '攻擊時展現驚人集中力時，恢復了自己的些許體力',
        ability_static_name: '靜電麻痺',
        ability_static_desc: '攻擊命中且點數極佳時，對方下一次攻擊變難以命中，且防禦與速度大幅下降',
        ability_decisive_name: '果斷出擊',
        ability_decisive_desc: '回合中當自己取得先手時，這回合對手的防禦力下降了',
        ability_foxdance_name: '狐舞連閃',
        ability_foxdance_desc: '攻擊命中時，下一個回合自己的防禦力提升了',
        ability_foxbait_name: '替狐誘餌',
        ability_foxbait_desc: '當對手取得先手時，對手的攻擊欲望降低了（攻擊變難以命中）',
        ability_fear_name: '恐懼凝視',
        ability_fear_desc: '攻擊命中時，下回合對手的反應變遲鈍了（速度下降）',
        ability_clawtie_name: '利爪繫命',
        ability_clawtie_desc: '多次造成傷害後，恢復了些許體力（每場限一次）',
        ability_venommist_name: '噬命毒霧',
        ability_venommist_desc: '連續取得先機後，回合結束使對方感到體力下降（每場限一次）',
        ability_toxicfang_name: '毒牙崩解',
        ability_toxicfang_desc: '戰鬥中初次造成傷害時威力大幅增強，但之後體力消耗極劇（永久攻擊變難以命中）',
        ability_dragarmor_name: '拖行裝甲',
        ability_dragarmor_desc: '攻擊命中後，下一回合因負重而休息不攻擊',
        ability_aurascatter_name: '聚氣散華',
        ability_aurascatter_desc: '攻擊命中時，下回合自己的防禦力下降了',
        ability_armormelt_name: '重甲解離',
        ability_armormelt_desc: '每回合結束時，自己的防守變得越來越薄弱（永久減防）',
        ability_brittlebone_name: '堅脆白骨',
        ability_brittlebone_desc: '成功格擋對手攻擊時，下回合自己的防禦力有所下降',
        ability_rageshell_name: '怒火熔殼',
        ability_rageshell_desc: '回合結束時，攻擊變準確的同時，防禦力也逐漸下降（永久）',
        ability_mistyarmor_name: '飄渺虛甲',
        ability_mistyarmor_desc: '回合中當自己取得先手時，自己的防守能力在短時間內變弱了',
        ability_sneakfang_name: '潛襲尖牙',
        ability_sneakfang_desc: '每次攻擊時都顯得極其精準（優勢判定）',
        ability_doomfist_name: '毀滅巨拳',
        ability_doomfist_desc: '採取捨身攻擊，命中不穩定但具毀滅性（必中判定但機率失常）',
        ability_exhausted_name: '過度力竭',
        ability_exhausted_desc: '攻擊命中且用力過猛時，自己也感到體力下降了',
        ability_wiltleaf_name: '秋風散葉',
        ability_wiltleaf_desc: '防禦成功但動作劇烈時，自己感到體力下降了',
        ability_lightscatter_name: '光散淋漓',
        ability_lightscatter_desc: '回合開始時若氣勢大幅落後對手，自己感到體力下降了',

        log_title: '   BATTOPO 戰鬥日誌 (Battle Log)',
        log_vs: '對戰雙方: {0} ({1}HP) vs {2} ({3}HP)',
        log_winner: '最終勝者: {0}',
        log_hp: '剩餘 HP : {0}:{1}  {2}:{3}',
        log_pre: '━━━━━ 戰鬥前階段 (Pre-Battle) ━━━━━',
        log_turn_header: '━━━━━ 第 {0} 回合 (Turn {0}) ━━━━━',
        log_spd: '速度對決: {0}({1}) vs {2}({3})',
        log_start: '[回合開始] {0}',
        log_end: '[回合結束] {0}',
        log_rest: '💤 {0} 正在休息，跳過回合',
        log_atk_title: '⚔️ {0} 攻擊 {1}:',
        log_adv: '優勢/取小',
        log_dis: '劣勢/取大',
        log_sum: '加總/毀滅',
        log_roll_info: '{0} [{1} (骰值: {2})]',
        log_atk_roll: '   - 攻擊擲骰: {0} (ATK: {1}) -> {2}',
        log_pbf: '   - 🛡️ 破防！連續格擋次數過高，無法格擋',
        log_def_roll: '   - 防禦擲骰: {0} (DEF: {1}) -> {2}',
        log_blk_true: '成功格擋',
        log_blk_false: '格擋失敗',
        log_dmg: '   - 最終傷害: {0}',
        log_trig: '   - [啟動] {0}: {1}',
        log_eof: '   戰鬥記錄結束',

        // Leave / Death Messages
        leave_hunger: '{0} 因為太餓了，決定離開去尋找食物...',
        leave_happy: '{0} 太不開心了，悄悄地離開了...',
        leave_poop: '{0} 受不了髒亂的環境，離開了...',
        leave_prompt_1: '想要再領養一隻新的寵物蛋嗎？',
        leave_prompt_2: '請在對話框輸入 <span style="color:var(--accent-fire);font-family:var(--font-pixel);font-size:12px;">egg</span> 重新開始',
        dead_msg: '{0} 已經安然離世了...',
        
        // Status Desc - Hunger
        stat_hunger_0: '飢腸轆轆',
        stat_hunger_1: '感覺好餓',
        stat_hunger_2: '有點肚子提示',
        stat_hunger_3: '肚子不餓',
        stat_hunger_4: '挺滿足的',
        stat_hunger_5: '感覺很飽',
        stat_hunger_6: '非常充實',
        
        // Status Desc - Happy
        stat_happy_0: '徹底心碎',
        stat_happy_1: '悶悶不樂',
        stat_happy_2: '有點無聊',
        stat_happy_3: '心情平靜',
        stat_happy_4: '感覺不錯',
        stat_happy_5: '很快樂',
        stat_happy_6: '興奮不已',
        
        // Status Desc - Poop
        stat_poop_0: '一塵不染',
        stat_poop_1: '有點小異味',
        stat_poop_2: '環境髒亂',
        stat_poop_3: '臭氣熏天',
        stat_poop_4: '快窒息了',
    },
    'en': {
        // UI Text
        ui_egg_name: '🥚 Egg',
        ui_egg: 'Egg',
        ui_hunger: '🍎 Hunger',
        ui_happy: '😊 Happy',
        ui_combat_start: 'Battle Starts!',
        ui_opponent: 'Opponent',
        ui_player: 'Player',
        ui_rps_title: '✌️ Rock-Paper-Scissors ✌️',
        ui_rps_desc: 'Type: <strong>scissors</strong>, <strong>rock</strong>, or <strong>paper</strong>',
        ui_scissors: 'Scissors',
        ui_rock: 'Rock',
        ui_paper: 'Paper',
        ui_feed_title: '🍎 Feed Pet 🍎',
        ui_feed_desc: 'Choose a fruit to feed:',
        ui_back: 'Back',
        ui_close: '✕ Close',
        ui_dex_title: '📖 Pokedex',
        ui_dex_progress: 'Progress: ',
        ui_hof_title: '🏆 Hall of Fame',
        ui_clean_title: '🚿 Bug Identification 🚿',
        ui_clean_hint: 'Enter the English name of the bug to clean it!',
        ui_hof_desc: 'In memory of the companions who accompanied us',
        ui_off: 'Off',
        ui_on: 'On',
        ui_hit: 'Hit',
        ui_miss: 'Miss',
        ui_blocked: 'Blocked',
        ui_dmg_taken: 'Failed, HP -{0}',
        ui_unknown: '???',
        ui_unknown_pet: 'Unknown Pet',
        ui_trait: 'Trait: ',
        ui_stage_baby: '▸ Initial Stage',
        ui_stage_1: '▸ Stage 1',
        ui_stage_2: '▸ Stage 2',
        ui_lang_title: '🌐 語言設定 / Language 🌐',
        ui_lang_desc: '選擇遊戲語言 / Select Game Language:',
        ui_lang_tooltip: 'Enter "lang" to open language settings',
        ui_cmd_prompt: 'Enter command...',
        ui_feed_placeholder: 'Enter fruit name or back...',
        ui_clean_placeholder: 'Enter bug name in English...',
        ui_lang_placeholder: 'english / chinese / japanese / back',
        ui_hof_placeholder: 'Enter back to return...',
        ui_rps_placeholder: 'Enter scissors, rock, or paper...',
        ui_knock_desc: 'Knock on the egg to see what happens',
        ui_clean_desc: 'Clean the pet and the environment',
        ui_play_desc: 'Play Rock-Paper-Scissors with your pet',
        ui_battle_desc: 'Challenge wild battles (Hunger >= 2)',
        ui_rename_desc: 'Give your companion a new name',
        ui_dex_desc: 'View the Pokedex of collected pets',
        ui_save_desc: 'Download save file for next time',
        ui_load_desc: 'Upload and load previous game progress',
        ui_evo1_timer: 'Stage 1 Evolution',
        ui_evo2_timer: 'Stage 2 Evolution',
        ui_death_timer: 'End of Lifespan',
        ui_evo_ready: '{0}: Ready anytime',
        ui_evo_time_d: '{0}: {1}d {2}h {3}m left',
        ui_evo_time: '{0}: {1}h {2}m left',
        
        // Fruit Names
        fruit_apple: 'Apple',
        fruit_orange: 'Orange',
        fruit_lemon: 'Lemon',
        fruit_grape: 'Grape',
        fruit_guava: 'Guava',

        // System messages
        msg_feed_prompt: '🍎 Type the english name of the fruit to feed, or type "back"',
        msg_feed_cant_battle: '⚔️ Cannot feed during battle!',
        msg_feed_full: '🍎 Hunger is full, no need to feed!',
        msg_dex_new: '📖 Added to Pokedex: ',
        msg_save_invalid: '❌ Invalid save file!',
        msg_save_corrupt: '❌ Failed to load save: file corrupted',
        msg_save_loaded: '📂 Save loaded successfully!',
        msg_save_downloaded: '💾 Save downloaded: ',
        msg_time_passed_hm: '⏰ {0} hours and {1} minutes since last save',
        msg_time_passed_m: '⏰ {0} minutes since last save',
        msg_come_back: ' is back!',
        msg_evolve: '✨ {0} evolved into {1}!',
        msg_evolve_stage1: '📊 Reached Stage 1 Evolution!',
        msg_hof_empty: 'No heroes recorded yet.',
        msg_hof_stats: '⚔️ Record: {0}W / {1}L (Win Rate: {2}%)',
        msg_rps_draw: '🤝 Draw! Both played {0}',
        msg_rps_win: '✌️ You won! {0} looks a bit disappointed...',
        msg_rps_lose: '🎉 {0} won! Now feeling {1}',
        msg_status_feed: '📊 Feeding Stats — {0}',
        msg_status_overall: '🏨 Status Summary — 🍔 Hunger: {0}  😊 Happy: {1}  🚿 Environment: {2}',
        msg_status_battle: '⚔️ Combat Stats — Wins: {0} / Battles: {1} (Win Rate: {2}%)',
        msg_status_evo1: '🔮 Based on current condition, Stage 1 evolution prediction: {0} ({1})',
        msg_status_evo2: '🔮 Based on current condition, Stage 2 evolution prediction: {0} ({1})',
        msg_status_evo_max: '⏳ Pet has reached final stage, remaining lifespan: 5 days',
        msg_welcome_back: 'Welcome back! Your {0} is waiting for you!',
        msg_rps_start: '✌️ RPS game starts! Please enter your choice...',
        msg_rps_invalid: '❌ Please enter: scissors, rock, or paper',
        msg_feed_invalid: '❌ Please enter fruit name: {0}',
        msg_feed_success: '{0} Fed {2} with {1}! Now feels {3}',
        msg_save_downloaded: '💾 Save downloaded: {0}',
        msg_save_loaded: '📂 Save loaded successfully! {0} is back!',
        msg_save_invalid: '❌ Invalid save file!',
        msg_time_passed: '⏰ Time passed since last save: {0}',
        msg_rename_prompt: '✏️ Please enter new name for {0}:',
        msg_rename_empty: '❌ Name cannot be empty!',
        msg_rename_long: '❌ Name up to 10 characters!',
        msg_rename_success: '✏️ {0} renamed to {1}!',
        msg_clean_cant_battle: '⚔️ Cannot clean during battle!',
        msg_clean_start: '🧹 Bug discovered! Please identify it by typing its English name.',
        msg_clean_wrong: '❌ Wrong name! Look closely and try again.',
        msg_clean_unnecessary: '🚿 Environment is clean, no need to clean!',
        msg_clean_success: '🚿 Cleaning done! Environment is now {0}',
        msg_play_cant_battle: '⚔️ Cannot play RPS during battle!',
        msg_battle_already: '⚔️ Battle is already in progress!',
        msg_battle_egg: '🥚 Egg is too young to battle!',
        msg_battle_tired: '💤 Pet is too tired (Hunger < 2), please feed!',
        msg_battle_no_opponent: '❌ Opponent not found, try again later.',
        msg_battle_win: '🎉 Battle Won! {0} feels very proud and happy!',
        msg_battle_lose: '💔 Battle lost... {0} ran away with its tail between its legs.',
        msg_battle_export_success: '💾 Battle details exported to battle_log.txt',
        msg_battle_export_download: '💾 Battle details downloaded (Local mode)',
        msg_egg_intro: '✨ You got a new egg! Type knock to interact!',
        msg_egg_knock: '🥚 The egg moved, type knock to interact!',
        msg_cmd_unknown_egg: '❌ Unknown command. Available: knock, dex, save, load',
        msg_cmd_unknown: '❌ Unknown command. Please enter a valid command.',
        msg_lang_set: '🌐 Language set to {0}.',
        msg_lang_invalid: '❌ Invalid language choice. Please type: english, chinese, or japanese',
        msg_battle_log_toggle: '⚔️ Detailed battle log is now {0}',
        msg_knock: '✊ Knock knock!',
        msg_egg_hatch: '✨ Hatched! {0} is born!',
        msg_time_passed_hm: '⏰ Time passed since last save: {0}h {1}m',
        msg_time_passed_m: '⏰ Time passed since last save: {0}m',
        msg_save_failed: '❌ Failed to load save: File format error',
        msg_dex_evolve: '✨ {0} evolved into {1}!',
        msg_dex_new: '📖 New Dex entry:',
        msg_hof_invalid: '❌ Invalid command. Type "back" to return.',
        msg_dex_invalid: '❌ Invalid command. Type "back" to return.',

        msg_debug_egg: '🥚 Cannot perform this action in egg stage!',
        msg_debug_stat: '🛠️ [DEBUG] {0} set to {1}',
        msg_debug_reset: '⚠️ [DEBUG] Game data has been reset!',
        msg_debug_dex_all: '🛠️ [DEBUG] Unlocked all {0} pet entries in Pokedex!',
        msg_debug_dex_clear: '⚠️ [DEBUG] Pokedex cleared!',
        msg_debug_death_err: '❌ [DEBUG] Only Stage 2 pets can perform this action!',
        msg_debug_hof_clear: '⚠️ [DEBUG] Hall of Fame cleared!',
        msg_debug_egg_hatch_err: '❌ [DEBUG] Please hatch the egg using "knock" first!',
        msg_debug_evo_err: '❌ [DEBUG] Pet is already at max stage!',
        msg_debug_evo1: '✨ [DEBUG] Triggered Stage 1 evolution!',
        msg_debug_evo2: '✨ [DEBUG] Triggered Stage 2 evolution!',
        msg_debug_feed: '🛠️ [DEBUG] {0} added {1}, total: {2}',
        msg_debug_feed_usage: '❌ [DEBUG] Usage: debugfeed [fruit_id] [amount]',
        msg_debug_setpet: '🛠️ [DEBUG] Pet form forced to {0} {1}!',
        msg_debug_setpet_usage: '❌ [DEBUG] Usage: debugsetpet [form_id]',


        msg_leave_hunger: '{0} was too hungry and left to find food...',
        msg_leave_happy: '{0} was too unhappy and quietly left...',
        msg_leave_poop: '{0} left because the environment was too dirty...',
        msg_leave_prompt: 'Want to adopt a new pet egg?',
        msg_leave_cmd: 'Type egg in the console to restart',
        msg_death: '{0} passed away peacefully...',
        msg_death_sub: 'Its life was wonderful. We will always remember it.',
        msg_battle_start: 'Encountered wild {0}! Battle start!',
        msg_battle_ability: '[{0}] {1}',
        msg_battle_dmg: 'Feels weaker',
        msg_battle_heal: 'Feels revitalized',
        msg_battle_atk_up: 'Attack becomes more accurate',
        msg_battle_atk_down: 'Attack becomes harder to hit',
        msg_battle_def_up: 'Defense increased',
        msg_battle_def_down: 'Defense decreased',
        msg_battle_spd_up: 'Became faster',
        msg_battle_spd_down: 'Became sluggish',
        msg_battle_dmg_up: 'Damage increased',
        msg_battle_turn: 'Turn {0} - Speed Roll!',
        msg_battle_attack: '{0} attacks!',
        msg_battle_blocked: '{0} successfully blocked!',
        msg_battle_hit: '{0} took damage!',
        msg_battle_miss: '{0} missed...',
        msg_battle_debug_spd: '🎲 [BATTLE] Turn {0} SPD: Player({1}) vs Enemy({2})',
        msg_battle_debug_atk: '🎲 [BATTLE] {0} ATK Roll: {1} (ATK:{2}) ({3})',
        msg_battle_debug_def: '🎲 [BATTLE] {0} DEF Roll: {1} (DEF:{2}) ({3})',

        battle_rest_name: 'Rest',
        battle_rest_msg: '{0} is resting, cannot attack',
        battle_crit_fail_name: 'Critical Failure',
        battle_crit_fail_msg: '{0} Critical Failure! The attack was too violent and hurt itself!',
        battle_crit_fail_debug: '{0} Rolled 20! The attack was too violent and hurt itself!',
        battle_weak_name: 'Weakness Exposed',
        battle_weak_msg: '{0} Weakness Exposed! Took extra damage',
        battle_weak_debug: '{0} Rolled 20! Fatal weakness exposed, took extra damage',
        battle_ability_dmg: '{0} affected by {1}, health decreased',
        battle_ability_heal: '{0} activated {1}, health restored',
        battle_ability_stat: '{0} affected by {1}, {2} {3}',
        battle_ability_stat_perm: '{0} affected by {1}, {2} permanently {3}',
        battle_ability_rest: '{0} affected by {1}, will rest next turn',
        battle_ability_mode: '{0} adopts {1} judgment',
        battle_ability_bonus: 'Activated {0}, dealt extra damage',

        // Abilities (Traits)
        ability_feather_name: 'Dazzling Feathers',
        ability_feather_desc: 'After being hit, force opponent to rest and make their attack harder to hit next turn',
        ability_vweb_name: 'Void Web',
        ability_vweb_desc: 'When hit by a low-roll attack, nullify damage and restore HP',
        ability_escape_name: 'Rapid Escape',
        ability_escape_desc: 'When hitting first in a turn, make opponent\'s attack harder to hit for that turn',
        ability_burnpunch_name: 'Burning Punch',
        ability_burnpunch_desc: 'Winning an attack decisively deals massive extra damage (Once per battle)',
        ability_fireball_name: 'Fireball',
        ability_fireball_desc: 'Ambush at start of battle, damaging opponent\'s health',
        ability_nrecover_name: 'Nature Recovery',
        ability_nrecover_desc: 'Small chance to restore self HP during an attack',
        ability_static_name: 'Static Paralysis',
        ability_static_desc: 'After a perfect hit, make opponent\'s attack harder to hit and decrease their DEF and SPD next turn',
        ability_decisive_name: 'Decisive Strike',
        ability_decisive_desc: 'When attacking first, decrease opponent\'s DEF for that turn',
        ability_foxdance_name: 'Fox Dance Flash',
        ability_foxdance_desc: 'When an attack hits, increase your DEF for the next turn',
        ability_foxbait_name: 'Fox Bait',
        ability_foxbait_desc: 'When opponent goes first, their attack becomes harder to hit',
        ability_fear_name: 'Fearful Gaze',
        ability_fear_desc: 'When an attack hits, decrease opponent\'s SPD next turn',
        ability_clawtie_name: 'Life-Link Claws',
        ability_clawtie_desc: 'Restore HP after dealing damage multiple times (Once per battle)',
        ability_venommist_name: 'Venom Mist',
        ability_venommist_desc: 'Deals damage at end of turn after multiple successful leads (Once per battle)',
        ability_toxicfang_name: 'Toxic Fang',
        ability_toxicfang_desc: 'Deals massive damage on first hit, but permanently makes own attack harder to hit',
        ability_dragarmor_name: 'Dragging Armor',
        ability_dragarmor_desc: 'After a hit, force self to rest next turn due to weight',
        ability_aurascatter_name: 'Aura Scatter',
        ability_aurascatter_desc: 'When an attack hits, decrease own DEF next turn',
        ability_armormelt_name: 'Armor Melt',
        ability_armormelt_desc: 'Lose DEF every turn end (Permanent)',
        ability_brittlebone_name: 'Brittle Bone',
        ability_brittlebone_desc: 'When blocking successfully, decrease own DEF next turn',
        ability_rageshell_name: 'Rage Shell',
        ability_rageshell_desc: 'Attack becomes more accurate but DEF decreases at every turn end (Permanent)',
        ability_mistyarmor_name: 'Misty Armor',
        ability_mistyarmor_desc: 'Decrease own DEF for the turn when taking the lead',
        ability_sneakfang_name: 'Sneak Fang',
        ability_sneakfang_desc: 'Every attack is extremely accurate (Advantage Roll)',
        ability_doomfist_name: 'Doom Fist',
        ability_doomfist_desc: 'Reckless attack style with massive damage but unstable aim',
        ability_exhausted_name: 'Over-Exhausted',
        ability_exhausted_desc: 'When hitting too hard, deal some self-damage',
        ability_wiltleaf_name: 'Wilted Leaf',
        ability_wiltleaf_desc: 'Violent evasive movements after block cause self-damage',
        ability_lightscatter_name: 'Light Scatter',
        ability_lightscatter_desc: 'Lose health if morale (SPD) is significantly lower than opponent',

        pet_baby: 'White Dot',
        pet_baby_black: 'Black Dot',
        pet_mud_pig: 'Mud Pig',
        pet_rainbow_dove: 'Rainbow Dove',
        pet_fire_rat: 'Fire Rat',
        pet_sprout_deer: 'Sprout Deer',
        pet_spark_cat: 'Spark Cat',
        pet_shadow_fox: 'Shadow Fox',
        pet_fist_lion: 'Fist Lion',
        pet_shadow_spider: 'Shadow Spider',
        pet_shadow_turtle: 'Shadow Turtle',
        
        pet_toxic_boar: 'Toxic Boar',
        pet_junk_boar: 'Junk Boar',
        pet_ghost_boar: 'Ghost Boar',
        pet_aurora_eagle: 'Aurora Eagle',
        pet_chaos_crow: 'Chaos Crow',
        pet_flash_falcon: 'Flash Falcon',
        pet_blast_rat: 'Blast Rat',
        pet_ash_rat: 'Ash Rat',
        pet_flame_rat: 'Flame Rat',
        pet_tree_deer: 'Tree Deer',
        pet_wind_deer: 'Wind Deer',
        pet_wilt_deer: 'Wilt Deer',
        pet_static_cat: 'Static Cat',
        pet_hunger_cat: 'Hunger Cat',
        pet_thunder_cat: 'Thunder Cat',
        pet_phantom_fox: 'Phantom Fox',
        pet_creep_fox: 'Creep Fox',
        pet_abyss_fox: 'Abyss Fox',
        pet_mega_lion: 'Mega Lion',
        pet_dirty_lion: 'Dirty Lion',
        pet_rage_lion: 'Rage Lion',
        pet_doom_spider: 'Doom Spider',
        pet_venom_spider: 'Venom Spider',
        pet_void_spider: 'Void Spider',
        pet_bone_turtle: 'Bone Turtle',
        pet_hellfire_turtle: 'Hellfire Turtle',
        pet_mirage_turtle: 'Mirage Turtle',

        pet_desc_baby: 'Small white organism with eyes, jumps slightly.',
        pet_desc_baby_black: 'A deep black dot, emitting a weak, dark aura.',
        pet_desc_mud_pig: 'A pig covered in mud, prefers messy environments.',
        pet_desc_rainbow_dove: 'A dove with feathers shining in five colors, representing balance.',
        pet_desc_fire_rat: 'A mouse with a tail burning with fire, has a very explosive personality.',
        pet_desc_sprout_deer: 'A small deer with sprouts growing on its head, loves nature.',
        pet_desc_spark_cat: 'A kitten with static in its fur, very agile movements.',
        pet_desc_shadow_fox: 'A secretive fox that can manipulate shadow orbs.',
        pet_desc_fist_lion: 'A lion with a tail as strong as a fist, incredible power.',
        pet_desc_shadow_spider: 'A spider lurking in the shadows with dangerous spikes.',
        pet_desc_shadow_turtle: 'A turtle with heavy Underworld armor, high defense.',
        pet_desc_toxic_boar: 'A giant boar living in toxic swamps with poisonous tusks.',
        pet_desc_junk_boar: 'A wild boar covered in trash used as armor.',
        pet_desc_ghost_boar: 'A spectral pig composed of resentment and mud.',
        pet_desc_aurora_eagle: 'A magnificent eagle soaring over the Arctic with aurora wings.',
        pet_desc_chaos_crow: 'A crow with chaotic feather colors, representing entropy.',
        pet_desc_flash_falcon: 'An incredibly fast falcon, moving like a flash of light.',
        pet_desc_blast_rat: 'A giant rat showing off explosive power.',
        pet_desc_ash_rat: 'A grey mouse that can move through ashes undetected.',
        pet_desc_flame_rat: 'A hunting expert surrounded by flames.',
        pet_desc_tree_deer: 'A giant deer fused with an ancient tree.',
        pet_desc_wind_deer: 'A herbivore that runs as fast as the wind.',
        pet_desc_wilt_deer: 'A deer skilled at hiding using wilted leaf colors.',
        pet_desc_static_cat: 'A black cat filled with high-voltage static electricity.',
        pet_desc_hunger_cat: 'A lightning cat that becomes fiercer due to hunger.',
        pet_desc_thunder_cat: 'A battle-hardened cat that controls thunder.',
        pet_desc_phantom_fox: 'A graceful fox that dances like a phantom.',
        pet_desc_creep_fox: 'A creepy fox that watches everything from the dark.',
        pet_desc_abyss_fox: 'A shadow fox from the abyss, completely consumed by darkness.',
        pet_desc_mega_lion: 'A fighting lion with devastating punching power.',
        pet_desc_dirty_lion: 'A brave opponent wearing armor made of dirt and sweat.',
        pet_desc_rage_lion: 'A fierce lion in a state of uncontrollable rage.',
        pet_desc_doom_spider: 'A giant spider wielding deadly scythe-like legs.',
        pet_desc_venom_spider: 'A terrifying spider covered in toxic crystals.',
        pet_desc_void_spider: 'A mysterious spider weaving silver webs across the void.',
        pet_desc_bone_turtle: 'A wild turtle whose shell has turned to bone.',
        pet_desc_hellfire_turtle: 'A giant turtle carrying magma and hellfire.',
        pet_desc_mirage_turtle: 'A translucent Underworld turtle that creates illusions.',

        log_title: '   BATTOPO Battle Log',
        log_vs: 'Versus: {0} ({1}HP) vs {2} ({3}HP)',
        log_winner: 'Final Winner: {0}',
        log_hp: 'Remaining HP : {0}:{1}  {2}:{3}',
        log_pre: '━━━━━ Pre-Battle ━━━━━',
        log_turn_header: '━━━━━ Turn {0} ━━━━━',
        log_spd: 'Speed Roll: {0}({1}) vs {2}({3})',
        log_start: '[Turn Start] {0}',
        log_end: '[Turn End] {0}',
        log_rest: '💤 {0} is resting, turn skipped',
        log_atk_title: '⚔️ {0} attacks {1}:',
        log_adv: 'Advantage',
        log_dis: 'Disadvantage',
        log_sum: 'Sum/Destroy',
        log_roll_info: '{0} [{1} (Rolls: {2})]',
        log_atk_roll: '   - ATK Roll: {0} (ATK: {1}) -> {2}',
        log_pbf: '   - 🛡️ Guard Broken! Block count too high.',
        log_def_roll: '   - DEF Roll: {0} (DEF: {1}) -> {2}',
        log_blk_true: 'Blocked',
        log_blk_false: 'Failed',
        log_dmg: '   - Final Damage: {0}',
        log_trig: '   - [Trigger] {0}: {1}',
        log_eof: '   End of Battle Log',

        // Leave / Death Messages
        leave_hunger: '{0} was too hungry and left to find food...',
        leave_happy: '{0} was too unhappy and quietly left...',
        leave_poop: 'The environment was too dirty, {0} has left...',
        leave_prompt_1: 'Want to adopt a new pet egg?',
        leave_prompt_2: 'Type <span style="color:var(--accent-fire);font-family:var(--font-pixel);font-size:12px;">egg</span> in the console to restart.',
        dead_msg: '{0} passed away peacefully...',
        
        // Status Desc - Hunger
        stat_hunger_0: 'Starving',
        stat_hunger_1: 'Very Hungry',
        stat_hunger_2: 'A bit hungry',
        stat_hunger_3: 'Not hungry',
        stat_hunger_4: 'Satisfied',
        stat_hunger_5: 'Very full',
        stat_hunger_6: 'Stuffed',
        
        // Status Desc - Happy
        stat_happy_0: 'Heartbroken',
        stat_happy_1: 'Depressed',
        stat_happy_2: 'Bored',
        stat_happy_3: 'Calm',
        stat_happy_4: 'Feeling good',
        stat_happy_5: 'Happy',
        stat_happy_6: 'Excited!',
        
        // Status Desc - Poop
        stat_poop_0: 'Spotless',
        stat_poop_1: 'Slight odor',
        stat_poop_2: 'Messy',
        stat_poop_3: 'Stinky',
        stat_poop_4: 'Suffocating',
    },
    'ja': {
        // UI Text
        ui_egg_name: '🥚 タマゴ',
        ui_egg: 'タマゴ',
        ui_hunger: '🍎 満腹度',
        ui_happy: '😊 ご機嫌',
        ui_combat_start: 'バトル開始！',
        ui_opponent: '相手',
        ui_player: 'プレイヤー',
        ui_rps_title: '✌️ じゃんけん ✌️',
        ui_rps_desc: '入力: <strong>scissors</strong>, <strong>rock</strong>, または <strong>paper</strong>',
        ui_scissors: 'チョキ',
        ui_rock: 'グー',
        ui_paper: 'パー',
        ui_feed_title: '🍎 ごはん 🍎',
        ui_feed_desc: 'あげる果物を選んでください：',
        ui_back: '戻る',
        ui_close: '✕ 閉じる',
        ui_dex_title: '📖 図鑑',
        ui_dex_progress: '収集率：',
        ui_hof_title: '🏆 殿堂入り',
        ui_clean_title: '🚿 むしのおそうじ 🚿',
        ui_clean_hint: 'むしさんの名前を入力してきれいにしましょう！',
        ui_hof_desc: '共に過ごした仲間たちへの追悼',
        ui_off: 'オフ',
        ui_on: 'オン',
        ui_hit: '命中',
        ui_miss: '失敗',
        ui_blocked: '防御成功',
        ui_dmg_taken: '防御失敗, HP -{0}',
        ui_unknown: '不明',
        ui_unknown_pet: 'なぞのペット',
        ui_trait: '特性：',
        ui_stage_baby: '▸ 初期形態',
        ui_stage_1: '▸ 第1形態',
        ui_stage_2: '▸ 第2形態',
        ui_lang_title: '🌐 語言設定 / Language 🌐',
        ui_lang_desc: '選擇遊戲語言 / Select Game Language:',
        ui_lang_tooltip: 'lang コマンドを入力して設定を開きます',
        ui_cmd_prompt: 'コマンドを入力...',
        ui_feed_placeholder: '果物名 または back...',
        ui_clean_placeholder: 'むしの英語名称を入力...',
        ui_lang_placeholder: 'english / chinese / japanese / back',
        ui_hof_placeholder: 'back と入力して戻る...',
        ui_rps_placeholder: 'scissors, rock, または paper...',
        ui_knock_desc: '卵を叩いて何が起きるか見てみよう',
        ui_clean_desc: 'ペットを掃除して環境をきれいにします',
        ui_play_desc: 'ペットとじゃんけんで遊びます',
        ui_battle_desc: '野生のバトルに挑戦 (満腹度2以上必要)',
        ui_rename_desc: '相棒に新しい名前を付けます',
        ui_dex_desc: '収集したペットの図鑑を見ます',
        ui_save_desc: '次回のプレイのためにセーブファイルを保存します',
        ui_load_desc: '以前のデータをロードします',
        ui_evo1_timer: '第1形態への進化',
        ui_evo2_timer: '第2形態への進化',
        ui_death_timer: '死期',
        ui_evo_ready: '{0}：いつでも可能',
        ui_evo_time_d: '{0}：残り {1}日 {2}時間 {3}分',
        ui_evo_time: '{0}：残り {1}時間 {2}分',

        // Fruit Names
        fruit_apple: 'リンゴ',
        fruit_orange: 'ミカン',
        fruit_lemon: 'レモン',
        fruit_grape: 'ブドウ',
        fruit_guava: 'グアバ',

        // System messages
        msg_feed_prompt: '🍎 あげる果物の英語名を入力するか、「back」で戻ってください',
        msg_feed_cant_battle: '⚔️ バトル中は餌をあげられません！',
        msg_feed_full: '🍎 お腹がいっぱいで、今は食べられません！',
        msg_dex_new: '📖 図鑑に登録：',
        msg_save_invalid: '❌ 無効なセーブデータです！',
        msg_save_corrupt: '❌ セーブの読み込みに失敗しました：ファイル破損',
        msg_save_loaded: '📂 セーブデータをロードしました！',
        msg_save_downloaded: '💾 セーブデータを保存しました: ',
        msg_time_passed_hm: '⏰ 前回の記録から {0} 時間 {1} 分が経過',
        msg_time_passed_m: '⏰ 前回の記録から {0} 分が経過',
        msg_come_back: ' が戻ってきました！',
        msg_evolve: '✨ {0} は {1} に進化した！',
        msg_evolve_stage1: '📊 第1形態へ進化しました！',
        msg_hof_empty: '殿堂入り記録はまだありません。',
        msg_hof_stats: '⚔️ 戦績: {0}勝 / {1}戦 (勝率: {2}%)',
        msg_rps_draw: '🤝 引き分け！お互い {0} を出した',
        msg_rps_win: '✌️ あなたの勝ち！ {0} は少しがっかりしている...',
        msg_rps_lose: '🎉 {0} の勝ち！今は {1} 気分',
        msg_status_feed: '📊 エサやり統計 — {0}',
        msg_status_overall: '🏨 ステータス — 🍔 満腹: {0}  😊 ご機嫌: {1}  🚿 環境: {2}',
        msg_status_battle: '⚔️ 戦績 — 勝利: {0} / 総対戦: {1} (勝率: {2}%)',
        msg_status_evo1: '🔮 現在の状態で予測される第1形態: {0} ({1})',
        msg_status_evo2: '🔮 現在の状態で予測される第2形態: {0} ({1})',
        msg_status_evo_max: '⏳ ペットは最終形態です。残り寿命: 5日',
        msg_welcome_back: 'おかえりなさい！ {0} が待っています！',
        msg_rps_start: '✌️ じゃんけん開始！選択を入力してください...',
        msg_rps_invalid: '❌ 入力してください: scissors, rock, または paper',
        msg_feed_invalid: '❌ 果物名を入力してください: {0}',
        msg_feed_success: '{0} {2} に {1} をあげました！今は {3} 気分',
        msg_save_downloaded: '💾 セーブデータをダウンロードしました: {0}',
        msg_save_loaded: '📂 セーブデータをロードしました！ {0} が戻ってきました！',
        msg_save_invalid: '❌ 無効なセーブデータです！',
        msg_time_passed: '⏰ 前回からの経過時間: {0}',
        msg_rename_prompt: '✏️ {0} の新しい名前を入力してください:',
        msg_rename_empty: '❌ 名前は空にできません！',
        msg_rename_long: '❌ 名前は最大10文字です！',
        msg_rename_success: '✏️ {0} は {1} に改名されました！',
        msg_clean_cant_battle: '⚔️ 戦闘中は掃除できません！',
        msg_clean_start: '🧹 むしを発見しました！英語名を入力して特定してください。',
        msg_clean_wrong: '❌ 名前が違います！よく見て、もう一度入力してください。',
        msg_clean_unnecessary: '🚿 環境はきれいです！掃除の必要はありません。',
        msg_clean_success: '🚿 掃除完了！環境は {0} になりました',
        msg_play_cant_battle: '⚔️ 戦闘中はじゃんけんできません！',
        msg_battle_already: '⚔️ すでに戦闘中です！',
        msg_battle_egg: '🥚 卵は小さすぎて戦えません！',
        msg_battle_tired: '💤 ペットが疲れています（満腹度2未満）。エサをあげてください！',
        msg_battle_no_opponent: '❌ 対戦相手が見つかりませんでした。',
        msg_battle_win: '🎉 バトルに勝利！{0} はとても誇らしげで、嬉しくなった！',
        msg_battle_lose: '💔 バトルに敗北... {0} は逃げ出してしまった。',
        msg_battle_export_success: '💾 戦闘ログを battle_log.txt に保存しました',
        msg_battle_export_download: '💾 戦闘ログをダウンロードしました（ローカル）',
        msg_egg_intro: '✨ 新しい卵を手に入れた！knock して叩いてみよう！',
        msg_egg_knock: '🥚 卵が動いた！knock して叩いてみよう！',
        msg_cmd_unknown_egg: '❌ 不明なコマンド。使用可能: knock, dex, save, load',
        msg_cmd_unknown: '❌ 不明なコマンドです。有効なコマンドを入力してください。',
        msg_lang_set: '🌐 言語が {0} に設定されました。',
        msg_lang_invalid: '❌ 無効な言語選択です。english, chinese, または japanese を入力してください。',
        msg_battle_log_toggle: '⚔️ 詳細バトルログが{0}になりました',
        msg_knock: '✊ コンコン！',
        msg_egg_hatch: '✨ 孵化した！{0}が誕生しました！',
        msg_time_passed_hm: '⏰ 前回からの経過時間: {0}時間 {1}分',
        msg_time_passed_m: '⏰ 前回からの経過時間: {0}分',
        msg_save_failed: '❌ セーブの読み込みに失敗しました：ファイル形式エラー',
        msg_dex_evolve: '✨ {0} は {1} に進化した！',
        msg_dex_new: '📖 図鑑に新登録：',
        msg_hof_invalid: '❌ 無効なコマンドです。backで戻ります。',
        msg_dex_invalid: '❌ 無効なコマンドです。backで戻ります。',

        msg_debug_egg: '🥚 卵の段階ではこの操作はできません！',
        msg_debug_stat: '🛠️ [DEBUG] {0} を {1} に設定しました',
        msg_debug_reset: '⚠️ [DEBUG] ゲームデータがリセットされました！',
        msg_debug_dex_all: '🛠️ [DEBUG] 全 {0} 種の図鑑を解放しました！',
        msg_debug_dex_clear: '⚠️ [DEBUG] 図鑑をクリアしました！',
        msg_debug_death_err: '❌ [DEBUG] 二段階進化後の形態のみ実行可能です！',
        msg_debug_hof_clear: '⚠️ [DEBUG] 殿堂入りデータをクリアしました！',
        msg_debug_egg_hatch_err: '❌ [DEBUG] 卵の状態です。まずは knock で孵化させてください！',
        msg_debug_evo_err: '❌ [DEBUG] すでに最終段階です！',
        msg_debug_evo1: '✨ [DEBUG] 第一段階進化を強制発動しました！',
        msg_debug_evo2: '✨ [DEBUG] 第二段階進化を強制発動しました！',
        msg_debug_feed: '🛠️ [DEBUG] {0} を {1} 追加しました。合計: {2}' ,
        msg_debug_feed_usage: '❌ [DEBUG] 使い方: debugfeed [果物名] [数量]',
        msg_debug_setpet: '🛠️ [DEBUG] ペットの形態を {0} {1} に強制設定しました！',
        msg_debug_setpet_usage: '❌ [DEBUG] 使い方: debugsetpet [形態ID]',

        msg_leave_hunger: '{0} はお腹が空きすぎて、食べ物を探しに去ってしまった...',
        msg_leave_happy: '{0} は悲しみのあまり、静かにどこかへ行ってしまった...',
        msg_leave_poop: '{0} は汚い環境に耐えられず、去ってしまった...',
        msg_leave_prompt: '新しい卵を育てたいですか？',
        msg_leave_cmd: 'コンソールに egg と入力してリスタート',
        msg_death: '{0} は安らかに息を引き取りました...',
        msg_death_sub: 'その生涯は素晴らしいものでした。',
        msg_battle_start: '野生の {0} が現れた！バトル開始！',
        msg_battle_ability: '[{0}] {1}',
        msg_battle_dmg: '体力が減った',
        msg_battle_heal: '体力が回復した',
        msg_battle_atk_up: '攻撃が正確になった',
        msg_battle_atk_down: '攻撃が当たりにくくなった',
        msg_battle_def_up: '防御力が上がった',
        msg_battle_def_down: '防御力が下がった',
        msg_battle_spd_up: '動きが俊敏になった',
        msg_battle_spd_down: '体が重くなった',
        msg_battle_dmg_up: 'ダメージが強化された',
        msg_battle_turn: '第 {0} ターン - 素早さ勝負！',
        msg_battle_attack: '{0} の攻撃！',
        msg_battle_blocked: '{0} は攻撃をブロックした！',
        msg_battle_hit: '{0} はダメージを受けた！',
        msg_battle_miss: '{0} の攻撃は外れた...',
        msg_battle_debug_spd: '🎲 [BATTLE] ターン {0} 速度: 自分({1}) vs 相手({2})',
        msg_battle_debug_atk: '🎲 [BATTLE] {0} 攻撃ロール: {1} (ATK:{2}) ({3})',
        msg_battle_debug_def: '🎲 [BATTLE] {0} 防御ロール: {1} (DEF:{2}) ({3})',

        battle_rest_name: '休息',
        battle_rest_msg: '{0} は休息中のため、攻撃できない',
        battle_crit_fail_name: '致命的失敗',
        battle_crit_fail_msg: '致命的失敗！勢い余って自分を傷つけてしまった！',
        battle_crit_fail_debug: '20を出した！勢い余って自分を傷つけてしまった！',
        battle_weak_name: '弱点露出',
        battle_weak_msg: '弱点露出！追加ダメージを受けた',
        battle_weak_debug: '20を出した！致命的な弱点を突き、追加ダメージを受けた',
        battle_ability_dmg: '{0} は {1} の影響を受け、体力が削られた',
        battle_ability_heal: '{0} は {1} を発動し、体力が回復した',
        battle_ability_stat: '{0} は {1} の影響を受け、{2} {3}',
        battle_ability_stat_perm: '{0} は {1} の影響を受け、{2} が永久に {3}',
        battle_ability_rest: '{0} は {1} の影響を受け、次ターン休息する',
        battle_ability_mode: '{0} は {1} 判定を採用した',
        battle_ability_bonus: '{0} を発動し、追加ダメージを与えた',

        // Abilities (Traits)
        ability_feather_name: '爆閃の羽',
        ability_feather_desc: '攻撃を受けた後、相手を次ターン休息させ、攻撃を当たりにくくする',
        ability_vweb_name: '虚空の網',
        ability_vweb_desc: '相手の低い出目での攻撃時、ダメージを無効化し体力を回復する',
        ability_escape_name: '迅速離脱',
        ability_escape_desc: '先手で攻撃が命中した時、そのターンの相手の攻撃を当たりにくくする',
        ability_burnpunch_name: '灼熱の拳',
        ability_burnpunch_desc: '攻撃が圧勝した際、追加ダメージを与える（バトル中一回）',
        ability_fireball_name: '火の玉投下',
        ability_fireball_desc: '戦闘開始時に奇襲を仕掛け、相手の体力を削る',
        ability_nrecover_name: '自然回復',
        ability_nrecover_desc: '攻撃時に集中力が極限に達すると、体力を少し回復する',
        ability_static_name: '静電麻痺',
        ability_static_desc: '攻撃が会心だった後、相手の攻撃を当たりにくくし、防御・速度を次ターン下げる',
        ability_decisive_name: '果断な一撃',
        ability_decisive_desc: '先手を取った時、そのターンの相手の防御力を下げる',
        ability_foxdance_name: '狐舞連閃',
        ability_foxdance_desc: '攻撃命中時、次のターンの自分の防御力を上げる',
        ability_foxbait_name: '身代わり狐',
        ability_foxbait_desc: '相手が先手の時、相手の攻撃意欲を削ぐ（攻撃が当たりにくくなる）',
        ability_fear_name: '恐怖の凝視',
        ability_fear_desc: '攻撃命中時、次ターンの相手の反応を鈍らせる（速度ダウン）',
        ability_clawtie_name: '繫命の爪',
        ability_clawtie_desc: 'ダメージを数回与えた後、体力を少し回復する（バトル中一回）',
        ability_venommist_name: '命を啜る毒霧',
        ability_venommist_desc: '先手を取り続けた後、ターン終了時に相手の体力を削る（一回）',
        ability_toxicfang_name: '毒牙崩壊',
        ability_toxicfang_desc: '最初の命中ダメージは絶大だが、以降は攻撃が永久に当たりにくくなる',
        ability_dragarmor_name: '鈍重な鎧',
        ability_dragarmor_desc: '攻撃命中後、鎧の重さで次のターンは休息する',
        ability_aurascatter_name: '聚氣散華',
        ability_aurascatter_desc: '攻撃命中時、次ターンの自分の防御力を下げる',
        ability_armormelt_name: '重甲解離',
        ability_armormelt_desc: 'ターン終了毎に自分の防御力が下がっていく（永久）',
        ability_brittlebone_name: '脆い白骨',
        ability_brittlebone_desc: 'ガード成功時、次ターンの自分の防御力が下がる',
        ability_rageshell_name: '怒りの熔殻',
        ability_rageshell_desc: 'ターン終了毎に攻撃が正確になり、防御が下がる（永久）',
        ability_mistyarmor_name: '朦朧たる虚甲',
        ability_mistyarmor_desc: '先手を取った際、自分の防御力が一時的に下がる',
        ability_sneakfang_name: '潜襲の尖牙',
        ability_sneakfang_desc: '全ての攻撃が極めて正確になる（優勢判定）',
        ability_doomfist_name: '破滅の巨拳',
        ability_doomfist_desc: '身を挺した攻撃で、命中には欠けるが絶大な威力を誇る',
        ability_exhausted_name: '過度の力尽き',
        ability_exhausted_desc: '全力の攻撃が命中した際、自分も少し疲弊する',
        ability_wiltleaf_name: '秋風散葉',
        ability_wiltleaf_desc: '激しい回避動作の末、自分も少し体力を消耗する',
        ability_lightscatter_name: '光散淋漓',
        ability_lightscatter_desc: '素早さで大きく引き離されている際、気力が散じ体力が減る',

        pet_baby: '白い点',
        pet_baby_black: '黒い点',
        pet_mud_pig: '泥豚',
        pet_rainbow_dove: '虹鳩',
        pet_fire_rat: '火ネズミ',
        pet_sprout_deer: '芽鹿',
        pet_spark_cat: '閃光猫',
        pet_shadow_fox: '影狐',
        pet_fist_lion: '拳銃ライオン',
        pet_shadow_spider: '影蜘蛛',
        pet_shadow_turtle: '冥亀',
        
        pet_toxic_boar: '毒沼猪',
        pet_junk_boar: '重装廃猪',
        pet_ghost_boar: '怨霊泥猪',
        pet_aurora_eagle: '極光天鷲',
        pet_chaos_crow: 'カオスカラス',
        pet_flash_falcon: '閃光ハヤブサ',
        pet_blast_rat: '爆炎巨鼠',
        pet_ash_rat: '灰燼潜鼠',
        pet_flame_rat: '烈焔狩鼠',
        pet_tree_deer: '古樹巨鹿',
        pet_wind_deer: '疾風草鹿',
        pet_wilt_deer: '枯葉隠鹿',
        pet_static_cat: '静電影猫',
        pet_hunger_cat: '飢雷迅猫',
        pet_thunder_cat: '雷霆戦猫',
        pet_phantom_fox: '幻影舞狐',
        pet_creep_fox: '飢影奇狐',
        pet_abyss_fox: '深淵影狐',
        pet_mega_lion: '熱拳戦獅子',
        pet_dirty_lion: '汚鎧闘獅子',
        pet_rage_lion: '激怒狂獅子',
        pet_doom_spider: '厄命鎌蜘蛛',
        pet_venom_spider: '猛毒晶蜘蛛',
        pet_void_spider: '虚空織網蜘蛛',
        pet_bone_turtle: '荒蕪骨亀',
        pet_hellfire_turtle: '獄炎岩亀',
        pet_mirage_turtle: '幽冥幻亀',

        pet_desc_baby: '目が付いた小さな白い生命体。軽く飛び跳ねる。',
        pet_desc_baby_black: '深い黒い点。微かな闇のオーラを放っている。',
        pet_desc_mud_pig: '全身泥まみれの豚。汚い環境を好む。',
        pet_desc_rainbow_dove: '五色の光を放つ羽を持つ鳩。均衡の象徴。',
        pet_desc_fire_rat: '尻尾に火が灯ったネズミ。非常に短気な性格。',
        pet_desc_sprout_deer: '頭に新芽が生えた小鹿。大自然を愛している。',
        pet_desc_spark_cat: '毛皮に静電気が溜まった子猫。動きが非常に俊敏。',
        pet_desc_shadow_fox: 'シャドウボールを操る狐。神秘的な雰囲気を漂わせる。',
        pet_desc_fist_lion: '拳のように強い尻尾を持つライオン。驚異的な力。',
        pet_desc_shadow_spider: '影に潜む蜘蛛。危険な棘を持っている。',
        pet_desc_shadow_turtle: '重厚な冥界の鎧を背負った亀。防御力が非常に高い。',
        pet_desc_toxic_boar: '毒の沼に住む巨大な豚。牙には猛毒がある。',
        pet_desc_junk_boar: 'ゴミを体に纏い、鎧代わりにしているイノシシ。',
        pet_desc_ghost_boar: '怨念と泥で構成された亡霊の豚。',
        pet_desc_aurora_eagle: '北極の上空を旋回する雄鷹。翼はオーラのよう。',
        pet_desc_chaos_crow: '羽の色が乱雑なカラス。混沌を象徴している。',
        pet_desc_flash_falcon: '極めて速いハヤブサ。その姿は閃光のよう。',
        pet_desc_blast_rat: '爆発的な威力を体現する巨大なネズミ。',
        pet_desc_ash_rat: '灰の中を気づかれずに移動できる灰色のネズミ。',
        pet_desc_flame_rat: '全身に炎を纏った狩りのエキスパート。',
        pet_desc_tree_deer: '古木と一体化した巨大な鹿。',
        pet_desc_wind_deer: '疾風のように速く走る草食獣。',
        pet_desc_wilt_deer: '枯れ葉の色を利用して身を隱すのが得意な鹿。',
        pet_desc_static_cat: '全身に高壓靜電を帶びた黑猫。',
        pet_desc_hunger_cat: '飢えにより異常に兇暴化した雷の猫。',
        pet_desc_thunder_cat: '百戰鍊磨で雷を操る戰闘猫。',
        pet_desc_phantom_fox: '幻影のように優雅に舞う狐。',
        pet_desc_creep_fox: '暗がりに隱れて全てを監視する不氣味な狐。',
        pet_desc_abyss_fox: 'アビスから来た、全身真っ黑な影の狐。',
        pet_desc_mega_lion: '壊滅的なパンチ力を持つ格闘ライオン。',
        pet_desc_dirty_lion: '泥と汗の鎧を纏った勇敢なライオン。',
        pet_desc_rage_lion: '激怒状態に陥った、誰にも止められない猛獅子。',
        pet_desc_doom_spider: '死の鎌のような腳を振るう巨大な蜘蛛。',
        pet_desc_venom_spider: '猛毒晶蜘蛛',
        pet_desc_void_spider: '虛空織網鋼蛛',
        pet_desc_bone_turtle: '荒蕪骨亀',
        pet_desc_hellfire_turtle: '獄炎岩亀',
        pet_desc_mirage_turtle: '半透明且能產生幻象的冥界烏龜',


        log_title: '   BATTOPO バトルログ',
        log_vs: '対戦: {0} ({1}HP) vs {2} ({3}HP)',
        log_winner: '最終勝者: {0}',
        log_hp: '残り HP : {0}:{1}  {2}:{3}',
        log_pre: '━━━━━ 戦闘前フェーズ ━━━━━',
        log_turn_header: '━━━━━ 第 {0} ターン ━━━━━',
        log_spd: '素早さ判定: {0}({1}) vs {2}({3})',
        log_start: '[ターン開始] {0}',
        log_end: '[ターン終了] {0}',
        log_rest: '💤 {0} は休んでいるため、ターンをスキップ',
        log_atk_title: '⚔️ {0} が {1} を攻撃:',
        log_adv: '有利',
        log_dis: '不利',
        log_sum: '合計/破壊',
        log_roll_info: '{0} [{1} (ダイス: {2})]',
        log_atk_roll: '   - 攻撃ロール: {0} (ATK: {1}) -> {2}',
        log_pbf: '   - 🛡️ ガードブレイク！防御回数が多すぎます',
        log_def_roll: '   - 防御ロール: {0} (DEF: {1}) -> {2}',
        log_blk_true: '防御成功',
        log_blk_false: '防御失敗',
        log_dmg: '   - 最終ダメージ: {0}',
        log_trig: '   - [発動] {0}: {1}',
        log_eof: '   バトルログ終了',

        // Leave / Death Messages
        leave_hunger: '{0} は空腹に耐えかね、食べ物を探しに去ってしまった...',
        leave_happy: '{0} は悲しみのあまり、静かにどこかへ行ってしまった...',
        leave_poop: '{0} はあまりの不潔さに耐えられず、去ってしまった...',
        leave_prompt_1: '新しいペットのタマゴを引き取りますか？',
        leave_prompt_2: '入力欄に <span style="color:var(--accent-fire);font-family:var(--font-pixel);font-size:12px;">egg</span> と入力して再スタート',
        dead_msg: '{0} は安らかに息を引き取った...',
        
        // Status Desc - Hunger
        stat_hunger_0: '腹ペコ',
        stat_hunger_1: 'かなり空腹',
        stat_hunger_2: '少し空腹',
        stat_hunger_3: '普通',
        stat_hunger_4: '満足',
        stat_hunger_5: 'お腹いっぱい',
        stat_hunger_6: '満腹',
        
        // Status Desc - Happy
        stat_happy_0: '絶望',
        stat_happy_1: '落ち込む',
        stat_happy_2: '退屈',
        stat_happy_3: '平穏',
        stat_happy_4: 'いい気分',
        stat_happy_5: 'ハッピー',
        stat_happy_6: '超ご機嫌！',
        
        // Status Desc - Poop
        stat_poop_0: 'ピカピカ',
        stat_poop_1: '少し匂う',
        stat_poop_2: '散らかっている',
        stat_poop_3: '臭すぎる',
        stat_poop_4: '息ができない',
    }
};

let currentLang = localStorage.getItem('battopo_lang') || 'zh-TW';

function t(key, ...args) {
    let text = errorFallback(key);
    if (!text) return key;

    for (let i = 0; i < args.length; i++) {
        text = text.replace('{'+i+'}', args[i]);
    }
    return text;
}

function errorFallback(key) {
    if (LANGUAGES[currentLang] && LANGUAGES[currentLang][key]) {
        return LANGUAGES[currentLang][key];
    }
    // Fallback to strict en or zh if key missing
    if (LANGUAGES['zh-TW'][key]) return LANGUAGES['zh-TW'][key];
    return null;
}

function switchLanguage(langCode) {
    if (LANGUAGES[langCode]) {
        currentLang = langCode;
        localStorage.setItem('battopo_lang', currentLang);
        updateLanguageUI();
        return true;
    }
    return false;
}

function updateLanguageUI() {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (key && LANGUAGES[currentLang][key]) {
            el.innerHTML = LANGUAGES[currentLang][key];
        }
    });

    // Fire custom event
    window.dispatchEvent(new Event('languageChanged'));
}
